on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # uv
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
            enable-cache: true

      # python and dependencies via uv
      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      # render
      - name: Render Quarto Project
        run: |
          uv run quarto render

      # publish to gh pages
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
